// ============================================================
//  Egg Breaker Adventures – Item Quotes
//  quotes.js  (loaded before data.js)
//
//  Edit the quotes here. Each key is the exact item display name.
//  Format: 'Item Name': '"Quote text."'
// ============================================================

const ITEM_QUOTES = {
  mr_monkey: {
    // Stage 1 – Tropical Paradise
    'Mango':              '"Let that mango."',
    'Coconut':            '"Put the lime in the coconut."',
    'Pineapple':          '"Who lives in a pineapple under the sea?"',
    'Golden Banana':      '"It\'s one banana. How much could it cost, $10?"',
    'Blood Orange':       '"Nobody can agree."',
    // Stage 2 – Jungle Trek
    'Parrot':             '"Norwegian Blue. Beautiful plumage."',
    'Tree Snake':         '"Why did it have to be snakes?"',
    'Gecko':              '"15 minutes could save you 15%."',
    'Leopard':            '"Spots: non-negotiable."',
    'Poison Frog':        '"Touch it. See what happens."',
    'Morpho Butterfly':   '"Float like a butterfly."',
    // Stage 3 – Ocean Depths
    'Octopus':            '"Eight arms. Zero patience."',
    'Clownfish':          '"Just keep swimming."',
    'Crab':               '"Sideways. Always sideways."',
    'Giant Squid':        '"Release the Kraken."',
    'Shark':              '"We\'re gonna need a bigger boat."',
    'Blue Whale':         '"Largest creature on Earth. Unimpressed."',
    // Stage 4 – Mountain Peak
    'Eagle':              '"The eagles are coming!"',
    'Mountain Goat':      '"GOAT. Literally."',
    'Bear':               '"Do not engage."',
    'Ancient Pickaxe':    '"And my axe."',
    'Snowy Owl':          '"Silent. Deadly. Disappointed."',
    'Peak Diamond':       '"Diamonds are forever."',
    'Crystal Summit':     '"Because it was there."',
    // Stage 5 – Desert Oasis
    'Camel':              '"Wednesday."',
    'Cactus Bloom':       '"Don\'t."',
    'Scorpion':           '"GET OVER HERE!"',
    'Ancient Vase':       '"It belongs in a museum!"',
    'Evil Eye Charm':     '"I\'m watching you, Wazowski."',
    'Golden Urn':         '"Contents: classified."',
    'Trident of Sands':   '"Wrong ocean. Right attitude."',
    // Stage 6 – Frozen Tundra
    'Penguin':            '"Smile and wave."',
    'Seal':               '"Sealed."',
    'Polar Bear':         '"Winter is coming."',
    'Arctic Fox':         '"Nothing. It\'s -40."',
    'Ice Crystal':        '"Chill."',
    'Diamond Dust':       '"All that glitters."',
    'Northern Star':      '"Second star to the right and straight on till morning."',
    // Stage 7 – Volcano Island
    'Lava Rock':          '"The floor is lava."',
    'Fire Opal':          '"Extremely hot take."',
    'Hot Spring Pearl':   '"Hot tub time machine? Close enough."',
    'Obsidian':           '"You shall not pass."',
    'Alchemist Stone':    '"Equivalent exchange."',
    'Lava Bubble':        '"I love gold. The look of it. The taste of it."',
    'Fire Diamond':       '"Forged in the fires of Mount Doom."',
    // Stage 8 – Enchanted Forest
    'Fairy':              '"I do believe in fairies."',
    'Magic Mushroom':     '"Not FDA approved."',
    'Unicorn':            '"Technically real."',
    'Dragon':             '"I am fire. I am death."',
    'Wizard':             '"You\'re a wizard."',
    'Elder Wand':         '"The wand chooses the wizard."',
    'Moonstone':          '"That\'s no moon."',
    'Stardust':           '"We are all made of star stuff."',
    // Stage 9 – Cloud Kingdom
    'Crown':              '"Heavy is the head."',
    'Ring of Power':      '"One ring to rule them all."',
    'Eternity Diamond':   '"Coal that did well under pressure."',
    'Crystal Ball':       '"Foggy. Like most futures."',
    'Champion Goblet':    '"To the victor."',
    'Royal Seal':         '"By royal decree."',
    'Rainbow Prism':      '"Somewhere over the rainbow."',
    'Wishing Star':       '"Wish carefully."',
  },
  steampunk: {
    // Stage 1 – Gear Workshop
    'Bronze Gear':        '"Keep turning."',
    'Steel Bolt':         '"Screwed? No. Bolted? Yes."',
    'Wrench':             '"Righty tighty."',
    'Chain Link':         '"Only as strong as its weakest link."',
    'Master Toolkit':     '"With great tools comes great responsibility."',
    // Stage 2 – Steam Engine Room
    'Steam Valve':        '"Let off some steam, Bennett."',
    'Brass Bell':         '"For whom the bell tolls."',
    'Clockwork':          '"Like clockwork."',
    'Magnet Core':        '"Attractive."',
    'Power Cell':         '"Unlimited power! (Terms apply.)"',
    'Tesla Battery':      '"Edison could never."',
    // Stage 3 – Airship Dock
    'Gas Cell':           '"Up, up, and away."',
    'Compass':            '"Why is the rum gone?"',
    'Telescope':          '"I can see my house from here."',
    'Sky Anchor':         '"Anchors aweigh."',
    'Antenna':            '"Can you hear me now?"',
    'Golden Chute':       '"Plan B."',
    // Stage 4 – Clocktower
    'Stopwatch':          '"Time waits for no monkey."',
    'Pocket Watch':       '"I\'m late."',
    'Grandfather Clock':  '"Tick tock. BONG."',
    'Hourglass':          '"Running out."',
    'Time Crystal':       '"Wibbly wobbly, timey wimey."',
    'Infinity Dial':      '"It\'s always egg o\'clock somewhere."',
    'Precision Spring':   '"Sproing. Technical term."',
    // Stage 5 – Laboratory
    'Light Bulb':         '"A bright idea."',
    'Microscope':         '"Yep. Still an egg."',
    'Radio':              '"Live from the workshop."',
    'Tesla Coil':         '"It\'s alive!"',
    'Spark Gap':          '"1.21 gigawatts?!"',
    'Master Blueprint':   '"I love it when a plan comes together."',
    'DNA Helix':          '"Life finds a way."',
    // Stage 6 – Underground Railway
    'Train Car':          '"I think I can."',
    'Golden Track':       '"All aboard."',
    'Travel Log':         '"First class. Obviously."',
    'Master Key':         '"It\'s dangerous to go alone. Take this."',
    'Secret Luggage':     '"WHAT\'S IN THE BOX?!"',
    'Lost Route Map':     '"X marks the spot."',
    'Signal Box':         '"Clear."',
    // Stage 7 – Copper Canyon
    'Copper Brick':       '"A penny for your thoughts."',
    'Silver Shard':       '"First loser."',
    'Gold Cube':          '"Do you expect me to talk? No, I expect you to smash."',
    'Raw Sapphire':       '"A gem."',
    'Bronze Medal':       '"Third."',
    'Tungsten Core':      '"Dense."',
    'Mythril Disc':       '"Unbreakable. Allegedly."',
    // Stage 8 – Sky Fortress
    'Rapier':             '"My name is Inigo Montoya..."',
    'Shield':             '"I can do this all day."',
    'Crossbow':           '"You have my bow. And my crossbow."',
    'Bomb':               '"Not yet."',
    'Dual Blades':        '"Why choose?"',
    'Boomerang':          '"I always come back."',
    'Mega Dynamite':      '"Bigger."',
    'Smoke Bomb':         '"Now you see me."',
    // Stage 9 – Time Nexus
    'Time Vortex':        '"Where we\'re going, we don\'t need roads."',
    'Paradox Gem':        '"This statement is false."',
    'Infinity Cog':       '"To infinity and beyond."',
    'World Globe':        '"It\'s a small world after all."',
    'Ancient Relic':      '"It belongs in a museum."',
    'Mask of Ages':       '"Somebody stop me!"',
    'Chrono Crystal':     '"Time is an illusion. Lunchtime doubly so."',
    'Eye of Time':        '"I\'ve seen things you people wouldn\'t believe."',
  },
  princess: {
    // Stage 1 – Royal Garden
    'Rose':               '"Stop and smell me."',
    'Tulip':              '"Beauty. On a schedule."',
    'Cherry Blossom':     '"Gone in two weeks. Worth it."',
    'Sunflower':          '"Always facing the light."',
    'Royal Bouquet':      '"Say it with flowers."',
    // Stage 2 – Grand Ballroom
    'Dance Shoes':        '"Made for dancing. Used for smashing."',
    'Music Box':          '"Wind it up."',
    'Royal Fan':          '"Not a fan of commoners."',
    'Masquerade Mask':    '"Behind every mask is another mask."',
    'Crystal Ball':       '"Disco never died."',
    'Grand Chandelier':   '"The music of the night."',
    // Stage 3 – Castle Tower
    'Tower Key':          '"The key."',
    'Ancient Scroll':     '"Read the fine print."',
    'Magic Candle':       '"Be our guest."',
    'Mirror Mirror':      '"Who\'s the fairest?"',
    'Rapunzel Thread':    '"Let down your hair."',
    'Knight Sword':       '"For king and country."',
    // Stage 4 – Royal Kitchen
    'Royal Cake':         '"Let them eat cake!"',
    'Cupcake':            '"Life is short."',
    'Golden Cookie':      '"That\'s the way the cookie crumbles."',
    'Tea Set':            '"I\'m a little teapot, short and stout."',
    'Chocolate Box':      '"Life is like a box of chocolates."',
    'Grand Gateau':       '"The cake is not a lie this time."',
    'Enchanted Candy':    '"I want it NOW, daddy!"',
    // Stage 5 – Royal Treasury
    'Diamond Ring':       '"If you liked it."',
    'Pearl Necklace':     '"Pearls of wisdom."',
    'Tiara':              '"Bow down, peasants."',
    'Royal Diamond':      '"A girl\'s best friend."',
    'Royal Brooch':       '"First."',
    'Fleur-de-lis':       '"Oui."',
    'Scepter Orb':        '"Kneel."',
    // Stage 6 – Dragon's Lair
    'Baby Dragon':        '"Step one: break the egg."',
    'Dragon Scale':       '"Dracarys."',
    'Dragon Egg':         '"Meta."',
    'Dragon Nest':        '"Not greedy. A collector."',
    'Dragonslayer':       '"FUS RO DAH!"',
    'Dragon Eye':         '"It noticed you."',
    'Dragon Heart':       '"To the stars that listen."',
    // Stage 7 – Enchanted Lake
    'Frog Prince':        '"Kiss at your own risk."',
    'Lotus Flower':       '"No mud, no lotus."',
    'Mermaid':            '"Part of the collection now."',
    'Swan':               '"Act II begins."',
    'Water Spirit':       '"Watching."',
    'Lake Trident':       '"Poseidon wants this back."',
    'Tear of the Lake':   '"The lake wept. It\'s fine."',
    // Stage 8 – Fairy Court
    'Fairy Queen':        '"Clap if you believe."',
    'Fairy Dust':         '"Faith, trust, and pixie dust."',
    'Magic Iris':         '"All-seeing. Quietly judging."',
    'Rainbow Butterfly':  '"Chaos theory. Look it up."',
    'Leaf Crown':         '"Very high fashion."',
    'Moon Tiara':         '"In the name of the Moon!"',
    'Pixie Wand':         '"Bibbidi-bobbidi-boo."',
    'Dream Bubble':       '"Pop."',
    // Stage 9 – Throne Room
    'Emperor Crown':      '"Uneasy lies the head."',
    'Excalibur':          '"Whoever pulls this sword from the egg..."',
    'Royal Shield':       '"I am no man."',
    'Royal Decree':       '"By royal decree."',
    'Lion Crest':         '"A Lannister always pays their debts."',
    'Castle Model':       '"Built on eggshells."',
    'Star of Royalty':    '"Born to rule."',
    'Kohinoor Diamond':   '"The Mountain of Light."',
  },
  space: {
    // Stage 1 – Launch Pad
    'Rocket':             '"Houston, we have an egg."',
    'Space Suit':         '"One small step."',
    'Satellite':          '"Orbiting. No big deal."',
    'Ground Dish':        '"Copy that."',
    'Star Scope':         '"To infinity and beyond."',
    // Stage 2 – Space Station
    'Lab Module':         '"For science!"',
    'Docking Pod':        '"Take me to your leader."',
    'Zero-G Tube':        '"In space, no one can hear you smash."',
    'Comms Array':        '"ET, phone home."',
    'Solar Panel':        '"Powered by the sun."',
    'Service Bot':        '"I\'m sorry, Dave."',
    // Stage 3 – Moon Base
    'Moon Rock':          '"One small rock."',
    'Regolith':           '"Fancy space dirt."',
    'Moon Crystal':       '"By the power of the moon!"',
    'Flag':               '"We come in peace."',
    'First Footprint':    '"One giant leap."',
    'Lunar Diamond':      '"Moon DIAMONDS."',
    // Stage 4 – Asteroid Belt
    'Comet Shard':        '"Technically a rock."',
    'Iron Meteorite':     '"Heavy metal."',
    'Stony Iron':         '"In space."',
    'Dark Asteroid':      '"Incoming."',
    'Space Diamond':      '"Dying star. Casual."',
    'Charged Fragment':   '"Electrifying."',
    'Pallasite':          '"Nature\'s gift wrap."',
    // Stage 5 – Mars Colony
    'Red Sand':           '"Mars ain\'t the kind of place to raise your kids."',
    'Olympus Stone':      '"Tallest volcano. Shortest patience."',
    'Ice Cap':            '"Ice, ice, baby."',
    'Mars Crystal':       '"Ancient Martian tech. Probably."',
    'Ancient Marker':     '"They were here."',
    'Alien Fossil':       '"The truth is out there."',
    'Valles Find':        '"The Grand Canyon called. It\'s jealous."',
    // Stage 6 – Jupiter Station
    'Storm Eye':          '"I am the storm."',
    'Ring Fragment':      '"Put a ring on it."',
    'Europa Ice':         '"Attempt no landing there."',
    'Io Lava':            '"Most volcanic body in the solar system. Mood."',
    'Atmo Sample':        '"Gas giant? I\'ve been called worse."',
    'Lightning Bolt':     '"Zeus wants this back."',
    'Pressure Diamond':   '"Worth it."',
    // Stage 7 – Nebula
    'Star Dust':          '"We are star stuff."',
    'Nebula Gas':         '"A cloud with an attitude."',
    'Baby Star':          '"Twinkle, twinkle."',
    'Red Giant Core':     '"Big, red, and about to blow."',
    'White Dwarf':        '"Small but mighty."',
    'Neutron Star':       '"Concentrated awesome."',
    'Pulsar Beacon':      '"716 times per second. I relate."',
    // Stage 8 – Black Hole Edge
    'Dark Particle':      '"Come to the dark side."',
    'Shadow Orb':         '"Shadow of a former self."',
    'Singularity':        '"Everything, eventually."',
    'Time Dilation':      '"Plan accordingly."',
    'Gravity Lens':       '"Bending light, breaking eggs."',
    'Hawking Crystal':    '"Not even light escapes."',
    'Event Horizon':      '"Point of no return."',
    'Infinity Shard':     '"I am inevitable."',
    // Stage 9 – Galaxy Core
    'Galaxy Map':         '"Don\'t panic."',
    'Quasar':             '"Brightest thing in the room."',
    'Supernova':          '"Going out with a bang."',
    'Life Seed':          '"The answer is 42."',
    'Cosmic Orb':         '"Probably."',
    'Infinity Stone':     '"Perfectly balanced."',
    'Spectrum Key':       '"Every color."',
    'Big Bang Shard':     '"In the beginning."',
  },
  odin: {
    // Stage 1 – Asgard
    'Thor\'s Blessing':       '"God of Thunder. Still not the sharpest."',
    'All-Seeing Eye':         '"Traded for wisdom. Debatable call."',
    'Bifröst Fragment':       '"No toll booth."',
    'Sleipnir\'s Shoe':       '"Eight legs. Eight bills."',
    'Gungnir Shard':          '"Never misses. Currently missing."',
    'Seiðr Rune':             '"Forbidden. The manual too."',
    // Stage 2 – Valhalla
    'Horn of Mead':           '"Drink deeply. Tomorrow you die again anyway."',
    'Einherjar Shield':       '"Survive until dinner."',
    'Sæhrímnir\'s Rib':       '"The boar reborn nightly. He\'s fine. Probably."',
    'Fallen Warrior\'s Helm': '"Died heroically. Seven times."',
    'Valkyrie\'s Horn':       '"Already too late. Or perfect timing."',
    'Eternal Glory':          '"Worth every axe wound."',
    // Stage 3 – Midgard
    'Longship Prow':          '"Surprisingly seaworthy."',
    'Dane Axe':               '"Not just for firewood. But also for firewood."',
    'Runic Sea Chart':        '"Here be everything terrible."',
    'Runic Amulet':           '"Wards off evil, attracts confused tourists."',
    'Antler Crown':           '"Don\'t ask about the antlers."',
    'Jormungandr Charm':      '"Still bites."',
    // Stage 4 – Jotunheim
    'Frost Rune':             '"Cold enough to freeze your Wi-Fi."',
    'Mountain Shard':         '"You\'ll never summit this."',
    'Fenrir\'s Milk Tooth':   '"He outgrew this. That\'s the scary part."',
    'Blizzard Vial':          '"Don\'t open indoors."',
    'Gleipnir Link':          '"Real materials. Allegedly."',
    'Thrym\'s Ice Crown':     '"He lost it to Thor in a dress. Long story."',
    // Stage 5 – Niflheim
    'Skull Rune':             '"Existential dread, postmarked."',
    'Mist Essence':           '"Bottled fog. Smells like cold inevitability."',
    'Eternal Candle':         '"Great ambiance. Terrible heating."',
    'Garm\'s Collar':         '"Very good boy. Do not approach."',
    'Hel\'s Crown':           '"Half gold, half bone. She was born this way. Literally."',
    'Void Shard':             '"Smells like nothing. Still ominous."',
    // Stage 6 – Muspelheim
    'Ember Rune':             '"Still hot. Always will be. Do not lick."',
    'Magma Stone':            '"Handle with optimism."',
    'Fire Opal':              '"Definitely not a piece of the sun. Probably."',
    'Surtr\'s Sliver':        '"Very long warranty."',
    'Nidhogg\'s Scale':       '"The roots aren\'t fine."',
    // Stage 7 – Yggdrasil
    'Heartwood Chip':         '"Centre of all nine realms. Still has sap."',
    'Ratatoskr\'s Acorn':     '"Knows everything. Tells everyone. Drama."',
    'Eagle\'s Feather':       '"Undefeated in staring contests."',
    'Nine Realms Leaf':       '"Heavier than it looks."',
    'Norns\' Thread':         '"Fate\'s loose end."',
    'Iðunn\'s Apple':         '"This one fell."',
    // Stage 8 – Ragnarök
    'Flood Tide Stone':       '"Collected just before."',
    'Fáfnir\'s Fang':         '"Lost arguing with Sigurd."',
    'Darkened Sun':           '"Brief period of solar inconvenience."',
    'Thunder Crack':          '"Thor\'s last lightning bolt. Bottled mid-chaos."',
    'Odin\'s Last Rune':      '"Half-finished. Very relatable."',
    'First New Leaf':         '"Hope, pressed and dried."',
    'Rebirth Spark':          '"The world ends. Also begins. Norse accounting."',
  },
};
