// ============================================================
//  Egg Breaker Adventures – Item Quotes
//  quotes.js  (loaded before data.js)
//
//  Edit the quotes here. Each key is the exact item display name.
//  Format: 'Item Name': '"Quote text."'
// ============================================================

const ITEM_QUOTES = {
  mr_monkey: {
    // Stage 1 – Tropical Paradise
    'Mango':              '"Forget your ex, Let that mango."',
    'Coconut':            '"Put the lime in the coconut."',
    'Pineapple':          '"Who lives in a pineapple under the sea?"',
    'Golden Banana':      '"It\'s one banana. How much could it cost, $10?"',
    'Blood Orange':       '"Orange you glad you found this?"',
    // Stage 2 – Jungle Trek
    'Parrot':             '"Norwegian Blue. Beautiful plumage."',
    'Tree Snake':         '"Why did it have to be snakes?"',
    'Gecko':              '"15 minutes could save you 15%."',
    'Leopard':            '"Why did it come out of an egg?"',
    'Poison Frog':        '"No touchy."',
    'Morpho Butterfly':   '"Float like a butterfly."',
    // Stage 3 – Ocean Depths
    'Octopus':            '"Cuttle Party?"',
    'Clownfish':          '"Just keep swimming."',
    'Crab':               '"You cannot teach a crab to walk straight."',
    'Giant Squid':        '"Release the Kraken."',
    'Shark':              '"We\'re gonna need a bigger boat."',
    'Blue Whale':         '"Whale Whale Whale, what do we have here?"',
    // Stage 4 – Mountain Peak
    'Eagle':              '"The eagles are coming!"',
    'Mountain Goat':      '"The GOAT."',
    'Bear':               '"Bearly enough hammers left right?"',
    'Ancient Pickaxe':    '"And my axe."',
    'Snowy Owl':          '"Hedwig? Not familiar."',
    'Peak Diamond':       '"Diamonds are forever."',
    'Crystal Summit':     '"Only downhill from here."',
    // Stage 5 – Desert Oasis
    'Camel':              '"Wednesday!"',
    'Cactus Bloom':       '"Free Hugs!"',
    'Scorpion':           '"GET OVER HERE!"',
    'Ancient Vase':       '"It belongs in a museum!"',
    'Evil Eye Charm':     '"You\'re safe as long as you have this."',
    'Golden Urn':         '"Nana?"',
    'Trident of Sands':   '"Wrong ocean buddy."',
    // Stage 6 – Frozen Tundra
    'Penguin':            '"Smile and wave boys."',
    'Seal':               '"Of approval."',
    'Polar Bear':         '"Winter is coming, right?"',
    'Arctic Fox':         '"Hatee-hatee-hatee-ho!"',
    'Ice Crystal':        '"Chill."',
    'Diamond Dust':       '"All that glitters."',
    'Northern Star':      '"Second star to the right and straight on till morning."',
    // Stage 7 – Volcano Island
    'Lava Rock':          '"The floor is lava."',
    'Fire Opal':          '"Tssss, hot."',
    'Secret Hot Springs':   '"Hot tub time machine? Close enough."',
    'Obsidian':           '"Apache tears."',
    'Alchemist Stone':    '"Equivalent exchange."',
    'Lava Bubble':        '"It\'s getting hot in here."',
    'Fire Diamond':       '"Burn, baby, burn."',
    // Stage 8 – Enchanted Forest
    'Fairy':              '"I do believe in fairies."',
    'Magic Mushroom':     '"Not FDA approved."',
    'Unicorn':            '"Technically real."',
    'Dragon':             '"I am fire. I am death."',
    'Wizard':             '"You shall not pass!"',
    'Elder Wand':         '"The wand chooses the wizard."',
    'Moonstone':          '"That\'s no moon."',
    'Stardust':           '"We are all made of star stuff."',
    // Stage 9 – Cloud Kingdom
    'Crown':              '"Heavy is the head."',
    'Ring of Power':      '"One ring to rule them all."',
    'Eternity Diamond':   '"Coal that did well under pressure."',
    'Crystal Ball':       '"It is decidedly so."',
    'Champion Goblet':    '"To the victor."',
    'Royal Seal':         '"By royal decree."',
    'Rainbow Prism':      '"Somewhere over the rainbow."',
    'Wishing Star':       '"Wish carefully."',
  },
  steampunk: {
    // Stage 1 – Gear Workshop
    'Bronze Gear':        '"Keep turning."',
    'Steel Bolt':         '"Tighten up."',
    'Wrench':             '"Need a handyman?"',
    'Chain Link':         '"Only as strong as its weakest link."',
    'Master Toolkit':     '"Can we fix it?"',
    // Stage 2 – Steam Engine Room
    'Steam Valve':        '"Let off some steam, Bennett."',
    'Brass Bell':         '"Ding!"',
    'Clockwork':          '"Like clockwork."',
    'Magnet Core':        '"I\'m attractive."',
    'Power Cell':         '"Unlimited power!"',
    'Battery':            '"Energized!"',
    // Stage 3 – Airship Dock
    'Gas Cell':           '"Up, up, and away."',
    'Compass':            '"Why is the rum gone?"',
    'Telescope':          '"I can see my house from here."',
    'Sky Anchor':         '"For flying... ships?"',
    'Antenna':            '"Can you hear me now?"',
    'Golden Chute':       '"Plan B."',
    // Stage 4 – Clocktower
    'Stopwatch':          '"Time waits for no monkey."',
    'Pocket Watch':       '"I\'m late."',
    'Grandfather Clock':  '"How did it get so late so soon?"',
    'Hourglass':          '"The wait will be worth it."',
    'Time Crystal':       '"Wibbly wobbly, timey wimey."',
    'Infinity Dial':      '"It\'s always egg o\'clock somewhere."',
    'Precision Spring':   '"Sproing. Look it up."',
    // Stage 5 – Laboratory
    'Light Bulb':         '"A bright idea."',
    'Microscope':         '"Yep. That\'s an egg."',
    'Radio':              '"Gossip is the Devil\'s radio."',
    'Tesla Coil':         '"Of all things, I liked books best."',
    'Spark Gap':          '"1.21 gigawatts?!"',
    'Master Blueprint':   '"I love it when a plan comes together."',
    'DNA Helix':          '"Life finds a way."',
    // Stage 6 – Underground Railway
    'Train Car':          '"I think I can."',
    'Golden Track':       '"All aboard!"',
    'Travel Log':         '"First class."',
    'Master Key':         '"The janitor lost this one."',
    'Secret Luggage':     '"It\'s not what\'s inside, it\'s the journey."',
    'Lost Route Map':     '"X marks the spot."',
    'Signal Box':         '"Life is the train. Not the station."',
    // Stage 7 – Copper Canyon
    'Copper Brick':       '"A penny for your thoughts."',
    'Silver Shard':       '"First loser."',
    'Gold Cube':          '"Do you expect me to talk? No, I expect you to smash."',
    'Raw Sapphire':       '"A gem. Can\'t buy groceries with it, but still nice."',
    'Bronze Medal':       '"Third place? Still good."',
    'Tungsten Core':      '"Are you dense?"',
    'Mythril Disc':       '"You can wear it under your outer clothes."',
    // Stage 8 – Sky Fortress
    'Rapier':             '"My name is Inigo Montoya..."',
    'Shield':             '"I can do this all day."',
    'Crossbow':           '"You have my bow."',
    'Bomb':               '"Kaboom!"',
    'Dual Blades':        '"There are worse things out tonight than vampires."',
    'Boomerang':          '"I always come back."',
    'Mega Dynamite':      '"Kaboom!!!"',
    'Smoke Bomb':         '"Now you see me."',
    // Stage 9 – Time Nexus
    'Time Vortex':        '"Where we\'re going, we don\'t need roads."',
    'Paradox Gem':        '"This statement is false."',
    'Infinity Cog':       '"To infinity and beyond."',
    'World Globe':        '"It\'s a small world after all."',
    'Ancient Relic':      '"Yup, it\'s old."',
    'Mask of Ages':       '"Somebody stop me!"',
    'Chrono Crystal':     '"Time is an illusion. Lunchtime doubly so."',
    'Eye of Time':        '"I\'ve seen things you people wouldn\'t believe."',
  },
  princess: {
    // Stage 1 – Royal Garden
    'Rose':               '"Stop and smell the roses."',
    'Tulip':              '"Flowers are restful to look at."',
    'Cherry Blossom':     '"Gone in two weeks."',
    'Sunflower':          '"Always facing the light."',
    'Royal Bouquet':      '"A dozen roses? How original."',
    // Stage 2 – Grand Ballroom
    'Dance Shoes':        '"Dancing is like dreaming with your feet!"',
    'Music Box':          '"Wind it up."',
    'Royal Fan':          '"Just a big fan."',
    'Masquerade Mask':    '"Everyone loves a good disguise."',
    'Crystal Ball':       '"Disco never died."',
    'Grand Chandelier':   '"The music of the night."',
    // Stage 3 – Castle Tower
    'Tower Key':          '"The key to my heart."',
    'Ancient Scroll':     '"End user license agreement."',
    'Magic Candle':       '"Candle in the wind."',
    'Mirror Mirror':      '"Who\'s the fairest?"',
    'Rapunzel Thread':    '"Let down your hair."',
    'Knight Sword':       '"For king and country."',
    // Stage 4 – Royal Kitchen
    'Royal Cake':         '"Let them eat cake!"',
    'Cupcake':            '"Cupcakes are muffins that believed in miracles."',
    'Golden Cookie':      '"That\'s the way the cookie crumbles."',
    'Tea Set':            '"I\'m a little teapot, short and stout."',
    'Chocolate Box':      '"Life is like a box of chocolates."',
    'Grand Gateau':       '"The cake is not a lie this time."',
    'Enchanted Candy':    '"Eat me."',
    // Stage 5 – Royal Treasury
    'Diamond Ring':       '"If you liked it."',
    'Pearl Necklace':     '"Pearls of wisdom."',
    'Tiara':              '"Bow down, peasants."',
    'Royal Diamond':      '"A girl\'s best friend."',
    'Royal Brooch':       '"A royal accessory."',
    'Fleur-de-lis':       '"Oui."',
    'Scepter Orb':        '"Cover yourself with glory, but also … with flannel!"',
    // Stage 6 – Dragon's Lair
    'Baby Dragon':        '"Wrong egg, Wrong egg!"',
    'Dragon Scale':       '"Dracarys!"',
    'Dragon Egg':         '"Keep it warm."',
    'Dragon Nest':        '"Shhh, it\'s sleeping."',
    'Dragonslayer':       '"FUS RO DAH!"',
    'Dragon Eye':         '"Come not between the dragon, and his wrath."',
    'Dragon Heart':       '"To the stars, Bowen, to the stars!"',
    // Stage 7 – Enchanted Lake
    'Frog Prince':        '"A kiss?"',
    'Lotus Flower':       '"No mud, no lotus."',
    'Mermaid':            '"In a world full of fish, be a mermaid."',
    'Swan':               '"Act II begins."',
    'Water Spirit':       '"Water is the softest thing, yet it can penetrate mountains."',
    'Lake Trident':       '"Poseidon wants this back probably."',
    'Tear of the Lake':   '"It\'s... wet."',
    // Stage 8 – Fairy Court
    'Fairy Queen':        '"Clap if you believe."',
    'Fairy Dust':         '"Faith, trust, and pixie dust."',
    'Magic Iris':         '"I just want you to know who I am."',
    'Rainbow Butterfly':  '"Chaos."',
    'Leaf Crown':         '"Very high fashion."',
    'Moon Tiara':         '"In the name of the Moon!"',
    'Pixie Wand':         '"Bibbidi-bobbidi-boo."',
    'Dream Bubble':       '"Pop."',
    // Stage 9 – Throne Room
    'Emperor Crown':      '"Uneasy lies the head."',
    'Excalibur':          '"Whoever pulls this sword from the egg..."',
    'Royal Shield':       '"I am no man."',
    'Royal Decree':       '"By royal decree."',
    'Lion Crest':         '"A Lannister always pays their debts."',
    'Castle Model':       '"Built on eggshells and Lego."',
    'Star of Royalty':    '"The brightest star in the kingdom."',
    'Kohinoor Diamond':   '"The Mountain of Light."',
  },
  space: {
    // Stage 1 – Launch Pad
    'Rocket':             '"Houston, we have a problem."',
    'Space Suit':         '"One small step."',
    'Satellite':          '"Finally the wifi is working."',
    'Ground Dish':        '"I\'m picking up weird signal."',
    'Star Scope':         '"To infinity and beyond."',
    // Stage 2 – Space Station
    'Lab Module':         '"For science!"',
    'Docking Pod':        '"Take me to your leader."',
    'Zero-G Tube':        '"Wheee!"',
    'Comms Array':        '"ET, phone home."',
    'Solar Panel':        '"Go green."',
    'Service Bot':        '"I\'m sorry, Dave."',
    // Stage 3 – Moon Base
    'Moon Rock':          '"It\'s basically cheese."',
    'Regolith':           '"Fancy space dirt."',
    'Moon Crystal':       '"By the power of the moon!"',
    'Flag':               '"We come in peace."',
    'First Footprint':    '"Hi, who put that there?"',
    'Lunar Diamond':      '"That looks expensive."',
    // Stage 4 – Asteroid Belt
    'Comet Shard':        '"Technically a rock."',
    'Iron Meteorite':     '"Don\'t take me for granite."',
    'Stony Iron':         '"I\'m a rock, I\'m an island."',
    'Dark Asteroid':      '"I\'m just a little meteorite."',
    'Space Diamond':      '"Dying star. Casual."',
    'Charged Fragment':   '"I\'m a shooting star."',
    'Pallasite':          '"Nature\'s gift wrap."',
    // Stage 5 – Mars Colony
    'Red Sand':           '"Mars ain\'t the kind of place to raise your kids."',
    'Olympus Stone':      '"That\'s where Zeus lives, right?"',
    'Ice Cap':            '"Ice, ice, baby."',
    'Mars Crystal':       '"Ancient Martian tech."',
    'Ancient Marker':     '"They were here."',
    'Alien Fossil':       '"The truth is out there."',
    'Valles Find':        '"I believe."',
    // Stage 6 – Jupiter Station
    'Storm Eye':          '"I am the storm."',
    'Ring Fragment':      '"Put a ring on it."',
    'Europa Ice':         '"Not for europeans."',
    'Io Lava':            '"Heyoooo!"',
    'Atmo Sample':        '"Gas giant? I\'ve been called worse."',
    'Lightning Bolt':     '"Zeus wants this back."',
    'Pressure Diamond':   '"Worth it."',
    // Stage 7 – Nebula
    'Star Dust':          '"We are star stuff."',
    'Nebula Gas':         '"Should not have eaten that."',
    'Baby Star':          '"Twinkle, twinkle."',
    'Red Giant Core':     '"Confused by all these space terms."',
    'White Dwarf':        '"Small but mighty."',
    'Neutron Star':       '"The densest thing in the universe. I think."',
    'Pulsar Beacon':      '"716 times per second."',
    // Stage 8 – Black Hole Edge
    'Dark Particle':      '"Come to the dark side."',
    'Shadow Orb':         '"Shadow of a former self."',
    'Singularity':        '"Everything, eventually."',
    'Time Dilation':      '"Plan accordingly."',
    'Gravity Lens':       '"Gravity... can cross the dimensions, including time."',
    'Hawking Crystal':    '"Not even light escapes."',
    'Event Horizon':      '"No, it\'s necessary."',
    'Infinity Shard':     '"I am inevitable."',
    // Stage 9 – Galaxy Core
    'Galaxy Map':         '"Don\'t panic."',
    'Quasar':             '"Brightest thing in the room."',
    'Supernova':          '"Going out with a bang."',
    'Life Seed':          '"The answer is 42."',
    'Cosmic Orb':         '"Probably."',
    'Infinity Stone':     '"Perfectly balanced."',
    'Spectrum Key':       '"Every color."',
    'Big Bang Shard':     '"In the beginning."',
  },
  odin: {
    // Stage 1 – Asgard
    'Thor\'s Blessing':       '"He dressed as a bride. Loki wore the veil."',
    'All-Seeing Eye':         '"One eye for all wisdom. Still outsmarted by Loki."',
    'Bifröst Fragment':       '"Sixteen million colors. No toll booth."',
    'Sleipnir\'s Shoe':       '"Eight legs. Loki\'s the mom. Move on."',
    'Gungnir Shard':          '"Never misses. Currently in pieces."',
    'Seiðr Rune':             '"Called unmanly. Odin did it anyway."',
    // Stage 2 – Valhalla
    'Horn of Mead':           '"Brewed by a rooftop goat. Five stars."',
    'Einherjar Shield':       '"Fight. Die. Feast. Repeat. Forever."',
    'Sæhrímnir\'s Rib':       '"Fully regrows each night. He\'s fine."',
    'Fallen Warrior\'s Helm': '"Freyja claims half the battle dead too."',
    'Valkyrie\'s Horn':       '"Chooser of the Slain. Great title."',
    'Eternal Glory':          '"540 doors. 800 warriors each. No queue."',
    // Stage 3 – Midgard
    'Longship Prow':          '"Dragon prows removed near friendly shores."',
    'Dane Axe':               '"Every free Viking was required to own weapons."',
    'Runic Sea Chart':        '"Vikings used sunstones to navigate the clouds."',
    'Runic Amulet':           '"Tiny Mjölnirs — top Viking jewelry for centuries."',
    'Antler Crown':           '"Loki has no horns in actual mythology."',
    'Jormungandr Charm':      '"Encircles the world. Bites its own tail."',
    // Stage 4 – Jotunheim
    'Frost Rune':             '"Some Jötnar are ancestors of the gods."',
    'Mountain Shard':         '"Thor\'s mom was Earth herself. Half giant."',
    'Fenrir\'s Milk Tooth':   '"He snapped every chain. This is a baby tooth."',
    'Blizzard Vial':          '"Loki and Odin are both part Jötunn."',
    'Gleipnir Link':          '"Made of six things that don\'t exist. Works."',
    'Thrym\'s Ice Crown':     '"Thor wore a wedding dress. Loki approved."',
    // Stage 5 – Niflheim
    'Skull Rune':             '"Niflheim predates the gods."',
    'Mist Essence':           '"Her plate is Hunger. Her knife, Famine."',
    'Eternal Candle':         '"Her hall is Éljúðnir. Her bed, Sick-Bed."',
    'Garm\'s Collar':         '"Guards the gate of Hel. Do not pet."',
    'Hel\'s Crown':           '"Half living, half dead. All business."',
    'Void Shard':             '"Before everything: fire, ice, and this."',
    // Stage 6 – Muspelheim
    'Ember Rune':             '"Older than the gods. Some fires just are."',
    'Magma Stone':            '"Surtr\'s retirement plan: burn everything."',
    'Fire Opal':              '"Sparks from here drifted out and became stars."',
    'Surtr\'s Sliver':        '"He\'s been ready since the very beginning."',
    'Nidhogg\'s Scale':       '"Gnaws Yggdrasil\'s roots. Never in a rush."',
    // Stage 7 – Yggdrasil
    'Heartwood Chip':         '"Three wells at its roots. It does a lot."',
    'Ratatoskr\'s Acorn':     '"His job: deliver insults between realms."',
    'Eagle\'s Feather':       '"A hawk subleases between the eagle\'s eyes."',
    'Nine Realms Leaf':       '"Nine realms. One tree. Vertical real estate."',
    'Norns\' Thread':         '"Was, Is, Shall Be. They weave. No undo."',
    'Iðunn\'s Apple':         '"Without these, the gods age and wither."',
    // Stage 8 – Ragnarök
    'Flood Tide Stone':       '"When the serpent rises, the seas follow."',
    'Fáfnir\'s Fang':         '"He was a dwarf. Gold made him a dragon."',
    'Darkened Sun':           '"Two wolves chase sun and moon. They win."',
    'Thunder Crack':          '"Thor slays it. Walks nine steps. Falls dead."',
    'Odin\'s Last Rune':      '"Fenrir swallows Odin. Víðarr tears him free."',
    'First New Leaf':         '"Two survivors hide in Yggdrasil. Life wins."',
    'Rebirth Spark':          '"Baldr returns. The world is reborn. Again."',
  },
};
